package com.example.launcher

import android.app.AlarmManager
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.net.Uri
import android.os.Build
import android.os.PowerManager
import android.provider.AlarmClock
import android.provider.Settings
import android.util.Log
import com.example.data.model.VoiceLearningLog
import com.squareup.moshi.JsonClass
import com.squareup.moshi.Moshi
import com.squareup.moshi.kotlin.reflect.KotlinJsonAdapterFactory
import java.net.URLEncoder
import java.util.Locale

/**
 * Standardized High-Level Action Structure representing native execution commands.
 * AI components may only generate these action objects, preventing direct coupling to native frameworks.
 */
@JsonClass(generateAdapter = true)
data class NativeExecutionAction(
    val actionType: String, // e.g., "LAUNCH_APP", "SYSTEM_SETTING", "DIAL", "SEND_SMS", "NAVIGATE", "SET_ALARM", "SHARE"
    val target: String = "", // package name, phone number, query search, or location
    val title: String = "", // sms body, map title, etc.
    val extraParams: Map<String, String> = emptyMap()
)

/**
 * Structured outcome describing execution results, to preserve modular status feedback.
 */
data class ExecutionOutcome(
    val success: Boolean,
    val message: String,
    val resolvedPackage: String? = null,
    val actionType: String
)

/**
 * Native Android Execution Layer
 * Encapsulates PackageManager queries, Intent resolution, system activity activation,
 * and application launching away from any AI model layer.
 */
class NativeExecutionLayer(private val context: Context) {

    private val moshi = Moshi.Builder().addLast(KotlinJsonAdapterFactory()).build()
    private val actionAdapter = moshi.adapter(NativeExecutionAction::class.java)

    /**
     * Executes an AI-generated action structure by converting it to native Android operations.
     */
    fun executeAction(action: NativeExecutionAction): ExecutionOutcome {
        Log.i("NativeExecutionLayer", "Request to execute native action: $action")
        return try {
            when (action.actionType.uppercase(Locale.getDefault())) {
                "LAUNCH_APP" -> launchApplication(action.target)
                "SYSTEM_SETTING" -> openSystemSetting(action.target)
                "DIAL" -> triggerDialer(action.target)
                "SEND_SMS" -> triggerSms(action.target, action.title)
                "NAVIGATE" -> triggerNavigation(action.target)
                "SET_ALARM" -> triggerAlarm(action.target, action.extraParams)
                "SHARE" -> triggerShare(action.title, action.target)
                else -> ExecutionOutcome(
                    success = false,
                    message = "Unknown action type: ${action.actionType}",
                    actionType = action.actionType
                )
            }
        } catch (e: Exception) {
            Log.e("NativeExecutionLayer", "Failure executing native action: ${action.actionType}", e)
            ExecutionOutcome(
                success = false,
                message = "Exception during native execution: ${e.message}",
                actionType = action.actionType
            )
        }
    }

    /**
     * Safely executes action modeled from a JSON string payload generated by an AI agent.
     */
    fun executeFromJson(jsonStr: String): ExecutionOutcome {
        return try {
            val action = actionAdapter.fromJson(jsonStr)
            if (action != null) {
                executeAction(action)
            } else {
                ExecutionOutcome(false, "Failed to parse JSON into NativeExecutionAction structure", "", "PARSE_ERROR")
            }
        } catch (e: Exception) {
            // If it is not a valid JSON, we fallback or return a clear diagnostic
            Log.w("NativeExecutionLayer", "Submitted string is not structured JSON action. Processing offline text action...")
            ExecutionOutcome(false, "Submitted payload is not a valid JSON structure: ${e.message}", "", "FORMAT_ERROR")
        }
    }

    /**
     * PackageManager: Launches an application by package name. Replaces indirect launch procedures.
     */
    private fun launchApplication(packageName: String): ExecutionOutcome {
        if (packageName.isBlank()) {
            return ExecutionOutcome(false, "Package name is blank", null, "LAUNCH_APP")
        }

        val pm = context.packageManager
        val launchIntent = pm.getLaunchIntentForPackage(packageName)
        if (launchIntent != null) {
            launchIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(launchIntent)
            return ExecutionOutcome(
                success = true,
                message = "Application '$packageName' launched successfully.",
                resolvedPackage = packageName,
                actionType = "LAUNCH_APP"
            )
        } else {
            // Fallback: If not installed, direct to play store description page
            return try {
                val storeIntent = Intent(Intent.ACTION_VIEW, Uri.parse("market://details?id=$packageName")).apply {
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                context.startActivity(storeIntent)
                ExecutionOutcome(
                    success = true,
                    message = "App '$packageName' not found. Redirected to Google Play Store details.",
                    resolvedPackage = "com.android.vending",
                    actionType = "LAUNCH_APP"
                )
            } catch (e: Exception) {
                ExecutionOutcome(
                    success = false,
                    message = "Failed to launch package '$packageName' and store details unavailable.",
                    actionType = "LAUNCH_APP"
                )
            }
        }
    }

    /**
     * Handles opening specialized system activity screens using Implicit / Explicit intents.
     */
    private fun openSystemSetting(settingType: String): ExecutionOutcome {
        val actionName = when (settingType.lowercase(Locale.getDefault())) {
            "wifi" -> Settings.ACTION_WIFI_SETTINGS
            "bluetooth" -> Settings.ACTION_BLUETOOTH_SETTINGS
            "display" -> Settings.ACTION_DISPLAY_SETTINGS
            "battery", "battery_saver" -> {
                if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.LOLLIPOP_MR1) {
                    Settings.ACTION_BATTERY_SAVER_SETTINGS
                } else {
                    Settings.ACTION_SETTINGS
                }
            }
            "location" -> Settings.ACTION_LOCATION_SOURCE_SETTINGS
            "accessibility" -> Settings.ACTION_ACCESSIBILITY_SETTINGS
            "date_time" -> Settings.ACTION_DATE_SETTINGS
            "network" -> Settings.ACTION_WIRELESS_SETTINGS
            "applications" -> Settings.ACTION_APPLICATION_SETTINGS
            else -> Settings.ACTION_SETTINGS
        }

        return try {
            val intent = Intent(actionName).apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            if (intent.resolveActivity(context.packageManager) != null) {
                context.startActivity(intent)
                ExecutionOutcome(true, "Opened system settings: $settingType.", null, "SYSTEM_SETTING")
            } else {
                // Secondary fallback
                val fallbackIntent = Intent(Settings.ACTION_SETTINGS).apply {
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                context.startActivity(fallbackIntent)
                ExecutionOutcome(true, "Setting $settingType target unavailable. Opened generic master Settings instead.", null, "SYSTEM_SETTING")
            }
        } catch (e: Exception) {
            ExecutionOutcome(false, "Error launching setting activity: ${e.message}", null, "SYSTEM_SETTING")
        }
    }

    /**
     * Standard dialer triggering via ACTION_DIAL
     */
    private fun triggerDialer(phoneNumber: String): ExecutionOutcome {
        return try {
            val cleanedNumber = phoneNumber.replace(Regex("[^+\\d]"), "")
            val intent = Intent(Intent.ACTION_DIAL, Uri.parse("tel:$cleanedNumber")).apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(intent)
            ExecutionOutcome(true, "Dialer opened for number: $cleanedNumber", null, "DIAL")
        } catch (e: Exception) {
            ExecutionOutcome(false, "Failed to open dialer activity: ${e.message}", null, "DIAL")
        }
    }

    /**
     * SMS Composer intent activation
     */
    private fun triggerSms(recipientNum: String, smsText: String): ExecutionOutcome {
        return try {
            val cleanedNum = recipientNum.replace(Regex("[^+\\d]"), "")
            val intent = Intent(Intent.ACTION_SENDTO).apply {
                data = Uri.parse("smsto:$cleanedNum")
                putExtra("sms_body", smsText)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(intent)
            ExecutionOutcome(true, "SMS composition screen opened for $cleanedNum", null, "SEND_SMS")
        } catch (e: Exception) {
            // Backup method
            return try {
                val backupIntent = Intent(Intent.ACTION_VIEW, Uri.parse("sms:$recipientNum")).apply {
                    putExtra("sms_body", smsText)
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                context.startActivity(backupIntent)
                ExecutionOutcome(true, "SMS opened with legacy backup view", null, "SEND_SMS")
            } catch (ex: Exception) {
                ExecutionOutcome(false, "Failed to activate SMS activity: ${ex.message}", null, "SEND_SMS")
            }
        }
    }

    /**
     * Map Navigation intent routing
     */
    private fun triggerNavigation(destination: String): ExecutionOutcome {
        if (destination.isBlank()) {
            return ExecutionOutcome(false, "Location query is blank", null, "NAVIGATE")
        }
        return try {
            val encodedQuery = URLEncoder.encode(destination, "UTF-8")
            val uriStr = "google.navigation:q=$encodedQuery"
            val mapIntent = Intent(Intent.ACTION_VIEW, Uri.parse(uriStr)).apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            if (mapIntent.resolveActivity(context.packageManager) != null) {
                context.startActivity(mapIntent)
                ExecutionOutcome(true, "Routing to coordinates or destination path: $destination", "com.google.android.apps.maps", "NAVIGATE")
            } else {
                // Open browser fallback maps page
                val webUri = Uri.parse("https://www.google.com/maps/search/?api=1&query=$encodedQuery")
                val webIntent = Intent(Intent.ACTION_VIEW, webUri).apply {
                    addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                }
                context.startActivity(webIntent)
                ExecutionOutcome(true, "Google Maps app missing. Fallback maps opened via Web Browser.", null, "NAVIGATE")
            }
        } catch (e: Exception) {
            ExecutionOutcome(false, "Maps activity execution failed: ${e.message}", null, "NAVIGATE")
        }
    }

    /**
     * Alarm Clock native activation
     */
    private fun triggerAlarm(titleStr: String, extraParams: Map<String, String>): ExecutionOutcome {
        return try {
            val hour = extraParams["hour"]?.toIntOrNull() ?: 7
            val minutes = extraParams["minutes"]?.toIntOrNull() ?: 0
            val skipUi = extraParams["skipUi"]?.toBoolean() ?: false

            val intent = Intent(AlarmClock.ACTION_SET_ALARM).apply {
                putExtra(AlarmClock.EXTRA_HOUR, hour)
                putExtra(AlarmClock.EXTRA_MINUTES, minutes)
                putExtra(AlarmClock.EXTRA_MESSAGE, titleStr.ifBlank { "NHN Workflow Quick Alarm" })
                putExtra(AlarmClock.EXTRA_SKIP_UI, skipUi)
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }

            if (intent.resolveActivity(context.packageManager) != null) {
                context.startActivity(intent)
                ExecutionOutcome(true, "Alarm registered natively for $hour:$minutes - '$titleStr'", null, "SET_ALARM")
            } else {
                ExecutionOutcome(false, "Device settings lack alarm resolver activity.", null, "SET_ALARM")
            }
        } catch (e: Exception) {
            ExecutionOutcome(false, "System alarm activity block failed: ${e.message}", null, "SET_ALARM")
        }
    }

    /**
     * Native share sheet trigger via ACTION_SEND
     */
    private fun triggerShare(titleText: String, messageBody: String): ExecutionOutcome {
        return try {
            val sendIntent = Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_TEXT, messageBody)
                putExtra(Intent.EXTRA_SUBJECT, titleText)
                type = "text/plain"
            }
            val shareIntent = Intent.createChooser(sendIntent, "NHN Share Portal").apply {
                addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            }
            context.startActivity(shareIntent)
            ExecutionOutcome(true, "System share sheet launched for message content.", null, "SHARE")
        } catch (e: Exception) {
            ExecutionOutcome(false, "Failed to launch device chooser intent: ${e.message}", null, "SHARE")
        }
    }

    /**
     * PackageManager: Queries all packages matching specified rules.
     */
    fun getInstalledAppsList(onlyUserApps: Boolean = true): List<AppMetaDataDetail> {
        val appList = mutableListOf<AppMetaDataDetail>()
        val pm = context.packageManager
        try {
            val packages = pm.getInstalledPackages(PackageManager.GET_META_DATA)
            for (p in packages) {
                val label = p.applicationInfo?.loadLabel(pm)?.toString() ?: continue
                val pName = p.packageName
                val isSys = (p.applicationInfo!!.flags and android.content.pm.ApplicationInfo.FLAG_SYSTEM) != 0
                val isEnabled = p.applicationInfo?.enabled ?: true

                if (onlyUserApps && isSys) {
                    continue
                }

                appList.add(
                    AppMetaDataDetail(
                        label = label,
                        packageName = pName,
                        isSystem = isSys,
                        isEnabled = isEnabled,
                        versionCode = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                            p.longVersionCode
                        } else {
                            @Suppress("DEPRECATION")
                            p.versionCode.toLong()
                        }
                    )
                )
            }
        } catch (e: Exception) {
            Log.e("NativeExecutionLayer", "Could not scan system packages", e)
        }
        return appList
    }
}

/**
 * Detailed Metadata model for the PackageManager list outputs
 */
data class AppMetaDataDetail(
    val label: String,
    val packageName: String,
    val isSystem: Boolean,
    val isEnabled: Boolean,
    val versionCode: Long
)
